- hosts: all
  vars:
    working_dir: /srv/locustio
  roles:
    - { role: configured, when: master or master__private_address is defined }
  tasks:
    - name: Install required packages.
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - python-pip
        - python-virtualenv
        - python-dev
        - gcc
        - g++
      tags:
        - install
        - upgrade-charm

    - name: Install pyzmq
      pip: name=pyzmq
           virtualenv={{ working_dir }}/env
      tags:
        - install
        - upgrade-charm

    - name: Install locustio
      pip: name=locustio
           virtualenv={{ working_dir }}/env
      tags:
        - install
        - upgrade-charm

    - name: Write user defined pip packages to charm_requirements.txt
      copy: content={{ pip_packages }}
            dest={{ working_dir }}/charm_requirements.txt
      tags:
        - config-changed

    - name: Install user defined pip packages
      pip: requirements={{ working_dir }}/charm_requirements.txt
           virtualenv={{ working_dir }}/env
      tags:
        - config-changed

    - name: Open port
      shell: open-port 8089
      tags:
        - install

    - name: No-op task for hooks without any tasks tagged.
      tags:
        - start
        - stop
      debug: msg="No ansible tasks tagged."
